trigger:
- master

resources:
- repo: self

variables:
  # container registry service connection established during pipeline creation - Docker Hub/ACR/...
  ContainerRegistry.ServiceConnection: '{{containerRegistryServiceConnection}}'
  # name of the container registry specified for above service connection
  ContainerRegistry.Name: '{{containerRegistry}}'
  Image.Name: '$(Build.Repository.Name)'
  Image.Tag: '$(Build.BuildId)'

  # Based on PORT in Dockerfile. Otherwise default value set
  Container.Port: {{containerPort}}

  # Details of the deployment target
  Azure.ServiceConnectionId: '{{ARMServiceConnection}}'
  FunctionApp.Name: '{{functionAppName}}'

jobs:
- job: Build
  displayName: Build
  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      repository: $(Image.Name)
      containerRegistries:
      - $(ContainerRegistry.ServiceConnection)

- deployment: Deploy to Function App for Containers
  displayName: Deploy
  dependsOn: Build
  steps:
  - task: AzureFunctionAppContainer@1
    displayName: Deploy to Function App for Containers
    inputs:
      azureSubscription: $(Azure.ServiceConnectionId)
      appName: $(FunctionApp.Name)
      imageName: $(ContainerRegistry.Name)/$(Image.Name):$(Image.Tag)
      appSettings: '-Port $(Container.Port)'