trigger:
- master

resources:
- repo: self

variables:
  # container registry service connection established during pipeline creation - Docker Hub/ACR/...
  ContainerRegistry.Serviceconnection: '{{containerRegistryServiceConnection}}'
  Image.Name: '$(Build.Repository.Name)'
  
steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:  
    repository: $(Image.Name)
    containerRegistries:
    - $(ContainerRegistry.ServiceConnection)