trigger:
- master

resources:
- repo: self

variables:
  # container registry service connection established during pipeline creation - Docker Hub/ACR/...
  ContainerRegistry.Serviceconnection: '{{containerRegistryServiceConnection}}'
  Image.Repository: '$(Build.Repository.Name)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(Image.Repository)
        containerRegistries: |
          $(ContainerRegistry.ServiceConnection)