trigger:
- master

resources:
- repo: self

variables:
  # container registry service connection established during pipeline creation - Docker Hub/ACR/...
  ContainerRegistry.Serviceconnection: '{{containerRegistryServiceConnection}}'
  Image.Repository: '$(Build.Repository.Name)'
  
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - use: docker
      auth:
      - $(ContainerRegistry.ServiceConnection)
    - script: |
        docker build -t $(ContainerRegistry.Name)/$(Image.Repository):$(Image.Tag)
        docker push $(ContainerRegistry.Name)/$(Image.Repository):$(Image.Tag)
      displayName: Build and push an image to container registry