trigger:
- master

resources:
- repo: self

variables:

 # Update Azure.ResourceGroupName value with Azure resource group name.
  Azure.ResourceGroupName: '{{#toAlphaNumericString repositoryName 50}}{{/toAlphaNumericString}}'

  # Update Azure.ServiceConnectionId value with AzureRm service endpoint.
  Azure.ServiceConnectionId: '{{azureServiceConnectionId}}'

  # Update Azure.Location value with Azure Location.
  Azure.Location: 'eastus'

  ContainerRegistry.ServiceConnection: '{{containerRegistryServiceConnection}}'
  ContainerRegistry.Name: '{{containerRegistry}}'

  Image.Repository: '$(Build.Repository.Name)'

jobs:

- job: CreateResources
  displayName: Create required resources
  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment:Create Azure Container Registry'
    inputs:
      azureSubscription: '$(Azure.ServiceConnectionId)'
      resourceGroupName: '$(Azure.ResourceGroupName)'
      location: '$(Azure.Location)'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/Microsoft/azure-pipelines-yaml/master/templates/resources/arm/acr.json'
      overrideParameters: '-registryName "$(ContainerRegistry.Name)" -registryLocation "$(Azure.Location)"'

- job: Build
  displayName: Build
  dependsOn: CreateResources
  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(Image.Repository)
      containerRegistries:
      - $(ContainerRegistry.ServiceConnection)